### PR TITLE
Add support for partial downloads + extra flags, add configurable build vars

### PR DESCRIPTION
**Pull request by junland**
PR adds additional logic to the `downloadSource` function in `bash.sh` to handle partial downloads in case internet connection is severed / interrupted during download, it also adds 3 retries with a 5 second delay between each retry. Explanation of the additional flags are explained [here](https://explainshell.com/explain?cmd=curl+-C+-+-L+--fail+--ftp-pasv+--retry+3+--retry-delay+5+-o+file.partial).

### CODE REVIEW

**Comment by junland** [comment]
Apparently I don't know how to do pull requests (Haven't done them all that much.). Anyways, I added configurable environment variables so that you can specify different vars for the `SERPENT_ARCH`, `SERPENT_HOST`, and `SERPENT_TRIPLET`. I've left the original values as the default as that was the default values anyways.

Doing this is simple.

```
cd stage1

SERPENT_ARCH=s390 SERPENT_TRIPLET=aarch64-serpent-linux-musl ./stage1 
```

This should hopefully lay the groundwork for different build archs in the future. See #9

**Comment by ikeycode** [comment]
Looking good so far but shouldn't the configurable vars be left in base.sh instead of duplication across stages?

**Comment by junland** [comment]
@ikeycode Yea, I thought that too. Though the way the scripts and build order are setup it makes it a hard to avoid duplicating vars. Since the individual stage scripts call `base.sh` you have to explicitly set the vars in the stage scripts. If we wanted to avoid having to duplicate the vars in `stage1.sh`, `stage2.sh`, `stage3.sh` etc. we would have to make it to where you build by executing `base.sh` then add a param to specify the stage. 

(Hopefully that makes sense, running on a few hours of sleep and a cup of coffee.)

```
# base.sh will be called build.sh

SERPENT_ARCH=s390 SERPENT_TRIPLET=aarch64-serpent-linux-musl ./build.sh stage1 
```

This will solve the duplicate vars, just add some more logic into `base.sh` and use that as your entry point script instead of `stage1.sh`, `stage2.sh`, etc. I could implement this, however it would change how you build everything. Would it be acceptable to add such functionality into the pull request?

**Comment by ikeycode** [comment]
Thanks bud, super appreciated!

**Comment by junland** [comment]
@ikeycode Okay new commits. That should be fixed now.

**Pull request merged**
